apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
  namespace: k8s-6-backend
  labels:
    app: backend
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /ocrImage
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
  namespace: k8s-6-backend
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      app: backend
