apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: test-k8s
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: taehoon981/backend:2.0
        ports:
        - containerPort: 3000
        env:
        - name: GUESTBOOK_DB_ADDR
          value: "mongodb-svc.test-k8s.svc.cluster.local:27017"  
        - name: PORT
          value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: test-k8s
  labels:
    app: backend
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: backend

