---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-from-sealedsecret
  namespace: k8s-6-db
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgB1jdTR3MwCKhG3IdbjjBJsweP2rZ7mMRqnXKsyu4136ikypNuW5Of/AKDO1/EO+63oaGe50n08woF9CiRhELwKgwsD7mksSF+8Pd0PD+keWHEPcwKAoSdm6uZ3ABfF0jVLswOnIi1/qnDAKTl5pKdCirxdq409UAfm9EToZw/G9/V/6H9BQXXvAIC294OoKrhoX9RtgOolkb5UVNxkk5o6jo5xQvD4LG/TzzRQodLyOb5jSrSYpoHdNaRewIz76LCp4oNENV26fgXMWx+0iiTPUi4x+XhyDrOY4ugpPV6o9ybfFabp9+xlgRgowsZaGQ2lbuC3sraGzCw5VDIsFeoxzoN64AUxWAZ+1VxgF6fX8XEkHMhqP/5wRODMqq+8QvXNAKcmzPJhZ4F7kwdLKsrnNX5e1ella/GA1ePd14fozikCOuEyyoOM/nzcXgKrOvfBUkD72b46rQBstx7bVZBM/f+ivUMPNTpjh7iZb+PqGY2QUck/uvtFNf8K21zbJUvxJUs9B+hPiYO1wWH668xzDk0DJfIJXBuaxj18qlhaB/0gn06pZofP6oUnnW77MP2gewzZfAoCd1Rwtg4iTUfAsFwnhmeVfh8NEpJUb+D37rxer78ysUsvI92cxzkx1rKESj8fW0nY8DcCA590PR2vAgW/TWbnOBsQW27OcPKqcbr94ZcGTq2s5xQurSN0Y80GyTV2K+HqSw==
  template:
    metadata:
      creationTimestamp: null
      name: secret-from-sealedsecret
      namespace: k8s-6-db
