apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: frontend
  namespace: k8s-6-frontend
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  metrics:                    
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 1
