apiVersion: v1
data:
  nginx.conf: |-
    events {
        worker_connections 1024;
    }

    http {
        upstream frontend {
            server localhost:3000;
        }

        server {
            listen 80 default_server;

            location / {
                proxy_pass http://frontend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: k8s-6-frontend

