apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.56.100
    path: /home/kevin/ocrImage

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv2
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.56.100
    path: /home/kevin/ocrImage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: back-nfs-pvc
  namespace: k8s-6-backend
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: front-nfs-pvc
  namespace: k8s-6-frontend
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

