apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-tempo
spec:
  capacity:
    storage: 10Gi  
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual  
  hostPath:
    path: /var/lib/tempo  
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-node2 
