apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-tempo
  namespace: k8s-6-monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual  

