apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: k8s-6-frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "true"
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: taehoon981/frontend:2.0
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: cf-front
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: k8s-6-frontend
  labels:
    app: frontend
spec:
  ports:
  - port: 3001
    targetPort: 3001
  type: NodePort
  selector:
    app: frontend

