apiVersion: v1
kind: PersistentVolume
metadata:
  name: frontend-pv
  namespace: frontend-ns
  labels:
    app: frontend
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data-dir/frontend-pv
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-pvc
  namespace: frontend-ns
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      app: frontend
