apiVersion: v1
kind: ResourceQuota
metadata:
  name: frontend-rq
  namespace: k8s-6-frontend
spec:
  hard: 
    pods: "10"
    requests.cpu: "150"
    requests.memory: "200Mi"
    limits.cpu: "400m"
    limits.memory: "400Mi"
