apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: k8s-6-backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: taehoon981/backend:2.0
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: cf-back 
        resources:
          requests:
            cpu: "10m"
            memory: 64Mi
          limits:
            cpu: "100m"
            memory: 120Mi    
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: k8s-6-backend
  labels:
    app: backend
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: backend
---
