apiVersion: v1
kind: ResourceQuota
metadata:
  name: db-quota
  namespace: k8s-6-db
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "8Gi"
    limits.cpu: "4"
    limits.memory: "16Gi"
    requests.storage: "200Gi"
    persistentvolumeclaims: "5"
