---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret
  namespace: k8s-6-db
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgC25NtEF4PXne4S5tC+ggMhdQ1Vcbi1RJ7MpTRLoyxxMa4gkBzuboBjggP08iKv1N/CVSvnMY+fZ1VGzdNmqRmiNKersgbqDnftGx1PycPFx/IqbiqOdiTdAd1kkfmzh1Z7isNyNl24yPrzsn/1BULV7jhZtB+11dHsq0Gnmw5rSvdAfLr62mvppxnEEKZJo5GLSWAExg40GB1bhDSfV5lCGqNbNsDxLD8oqyG2z9uDeF5rGT6qFTwfwAoMIie0hqpCMHiG1I1YO99dsaeKQDKnkI8EP7Rv4NQJ/molMrmpm2P5xU6gfvAG7S004f5aDQJsBqzknnFU5fQG13ALWEzn/L+fruHrM+jKU2jxZInEXuwKpOVRDpKIXmjJMF9Q8QOQljpoDYs3oHz5ynHCqj2o+n8N1nkSg9MJ1fFdxIMBVVre58OwibA9v57/RsjAoXooxQ7OyWDoT/7xZaTbuom9od90+Kv0ksM/nv+MWI/pJVAkZAyKyeMuuHvVGKLT8qFcGdnpavsnwOcpPzMaWqdwdPk5qscCqqMUnHaenJWlqD+scwG+qVLqKC5QdtvSZtwEhXi2qb9zIsC8W7SRvp2n2GSCmt1b9ZXkErsxsfe5/OMVekrHD9oz6lxQngeH/5hZY8giQt2+2i/PG8EDToJxY2/YqWFTw75fyQZweMDcuqvcDlo3hUTAaMH0UwWKunW0NzwLvPFp0A==
  template:
    metadata:
      creationTimestamp: null
      name: secret
      namespace: k8s-6-db
