apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: monitoring-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - persistentvolumenonResourceURLs:[trace]
