apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: db-sa
  namespace: db-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: frontend-sa
  namespace: frontend-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: backend-sa
  namespace: backend-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: monitoring-sa
  namespace: monitoring-ns
