---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret
  namespace: db-ns
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgCBB8DB7yALTq51GO54nI7lOZewZHTh09uYUocro91TZvKrg0OJBGjz7OjZrcc67KCNhHnNsrobb27u6qFSjoqkuPHdjF/ICMoxGhg5aF8y+fnD2PwUPSpgy6LvJDIrSBRyda++qUHrx/tgYzpy+JkOP7ve59H8u3X4fKoangMRTxIVYC/OP/NodFscA8FaNBxL7WjrCW+dnQ4C5RDhE5jfAHRG0h6UxjtmE3MYTUY7lw/5IQJHINyj51FkbhyxPyKP3FukwzUJPDtn7QI8sOBBjgyiBv4qnfRRAN678RhK45e9YuWcJ14C/9rLpZXPxmcbyzJpWUAKD+Kf8RhgR0sDOWQEpgQDy1HWQX6OOf3dCJuM6C4y4WjIBcqHmjsQ/liAY5NRTT5tGmcLH2DnG3/+siRMGnt484sj9Hx37wya9XUcdcUA1osNAs08tEUOXOM1xsbBA+irJEW+25obmJOFp9deFW8P4wWbDXDQBbxn/sb3fo+0x97ni+E6apXkmXkeIs0CUY2nljZM8ZSlEj0yd/4XOImD7FxdXc0070DDw6YnJae2LolYUg6JwvbL0DkCuIREtBRfYyWIe20GrETBJL0D31Mne3K5jwFXFScA0fghUqEpm59IpUCP5U2Is4ROUjaxJBxuQ672CyEU01xWq7YQNm0aRriilEtFNPFiMyG4HjwbZorcQePghkOxi2T34jaVLLCvgA==
  template:
    metadata:
      creationTimestamp: null
      name: secret
      namespace: db-ns
