spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accountbook
    #url: jdbc:mysql://${MYSQL_HOST}:3306/accountbook
    username: root
    #username: ${MYSQL_USER}
    password: 245245
    #password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

cloud:
  google:
    storage:
      bucket:
        name: k8s_receipt_bucket
        filePath: gs://k8s_receipt_bucket/