apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: k8s-6-db
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.0
        ports:
        - containerPort: 27017
        envFrom:
        - configMapRef:
            name: cf-db
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: k8s-6-db
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb

