apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openebs-mysql-pvc
  namespace: k8s-6-db
spec:
  storageClassName: "openebs-hostpath"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi


